# Docker compose file for the application on Digital Ocean.
# run
# sudo apt-get -y install python-pip
# sudo pip install docker-compose

#version: '2'   # on CircleCI the version and services cause build to puke.
#services:
  frontend:
    image: harbor.dev.o19s.com/search-viz/app:latest
    ports:
     - "8080:80"
